### ISSUE TITLE
Adding proper header file

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-mailgen#3]
The main file in my view needs a header file stating the authors, copyright and license.

And: BTW: shouldn't be #!/usr/bin/env python3 to be sure?

**Comment by bernhard-herzog** [comment]
The part aboud python3 in the #!-line has been fixed in 
https://github.com/Intevation/intelmq-mailgen/commit/28ec619a267cbe6a68a902ca558f64dc22341be5

**Comment by bernhardreiter** [comment]
@dmth is there still something to do, as you did not resolve this issue?

**Comment by dmth** [comment]
Thank you for tidying up the old issues. This should be resolved by now.
